@startuml ModeloMVC

hide empty attributes

package "Main"{
	'Main's
	class AplicacionMVC
	class GestorGeneral
}

'Controladores
package "Controlador"{
	abstract class Controlador
	class ControladorImplHome
	class ControladorImplBuscarUsuario
	class ControladorImplRegistrarTurnoBD
	class ControladorImplRegistrarEntregaBD
}



package "Vista"{
	'Vistas
	interface InterfazVista	
	class VistaHome
	class VistaTurno
	class VistaRegistroTurno
	class VistaEntrega
}


package "Modelo"{
	'Modelos
	class Modelo
	package "Factory Method Persona"{
		abstract class Persona{
			+ getNombre()
		}

		abstract class Empleado{
			+ atender()
		}
		
		abstract class PersonaFactoryMethod{
			+ crearPersona( id )
		}

		' Implementacion
		' 1 - Cliente
		' 2 - Empleado
		' 3 - Mecanico
		class PersonaFactory{
			+ crearPersona ( id )
		}
		class Cliente{
			+ quejarse()
		}
		class Mecanico{
			+ arreglar()
		}
		class Oficinista{
			+ llamar()
		}
		PersonaFactory -left-|> PersonaFactoryMethod
		PersonaFactory ..> Cliente : <<instancia>>
		PersonaFactory ..> Mecanico : <<instancia>>
		PersonaFactory ..> Oficinista : <<instancia>>
		Cliente --|> Persona
		Empleado -left-|> Persona

		Mecanico --|> Empleado
		Oficinista --|> Empleado
	}

	package "DAO" <<Database>>{

		
		package "FabricaDAO"{
			interface EmpleadoDAO
			interface ClienteDAO
			interface TurnoDAO

			abstract class FabricaDAO

			class ClienteDAOImpl
			class EmpleadoDAOImpl
			class TurnoDAOImpl
			class ConexionSQLite
			class SqlFabricaDAO

		}

		EmpleadoDAOImpl -up-> ConexionSQLite 
		ClienteDAOImpl -up-> ConexionSQLite
		TurnoDAOImpl -up-> ConexionSQLite 
		EmpleadoDAOImpl ..|> EmpleadoDAO
		ClienteDAOImpl ..|> ClienteDAO
		TurnoDAOImpl ..|> TurnoDAO
		SqlFabricaDAO -up-|> FabricaDAO
		SqlFabricaDAO ..> EmpleadoDAOImpl
		SqlFabricaDAO ..> TurnoDAOImpl
		SqlFabricaDAO ..> ClienteDAOImpl


	}
}



GestorGeneral ..> FabricaDAO : <<usa>>
GestorGeneral.. Empleado
GestorGeneral .. Cliente
GestorGeneral ..> ClienteDAO
GestorGeneral ..> EmpleadoDAO
GestorGeneral ..> TurnoDAO

'Relaciones
'Controlador
Controlador <|-- ControladorImplHome
Controlador <|-- ControladorImplBuscarUsuario
Controlador <|-right- ControladorImplRegistrarTurnoBD
Controlador <|-- ControladorImplRegistrarEntregaBD

ControladorImplRegistrarEntregaBD ..> GestorGeneral : <<usa>>
ControladorImplRegistrarTurnoBD ..> GestorGeneral : <<usa>>
ControladorImplBuscarUsuario ..> GestorGeneral : <<usa>>

Controlador ..> Modelo : <<manipula>>
Controlador ..> InterfazVista : <<actualiza>>

'Main
AplicacionMVC .left.> Controlador : <<usa>>

'Interfaz
InterfazVista ..> Controlador
VistaHome ..|> InterfazVista
VistaTurno ..|> InterfazVista
VistaRegistroTurno ..|> InterfazVista
VistaEntrega ..|> InterfazVista

@enduml