@startuml Empresa
package Empresa{

    'hide empty methods
    Class Empresa{
        -nombre_empresa: string
    }

    Abstract Class Persona{
        -nombre: String
        -apellido: String
        -dni: String
        -direccion: Direccion
        -telefono: Telefono
   }

    Abstract Class Empleado{
        -jefe: Empleado
        -datosEmpleado: Persona
        -legajo:int
    }

    Class Vehiculo {
        -nombre: String
        -marca: String
        -patente: String
    }
    

    Class CompaniaSeguros{
        -razónSocial: string
        -cuit: int
    }

    Class Mecanico{
        -datosMecanico: Empleado
        -especialidad: Especialidad
	-turno: string
    }

    Class Oficinista{
        -datosOficinista: Empleado
     } 

    Class Especialidad{
        -id: int
        -nombre: String
    }

    'Hija de Persona
    Class Cliente{
        -nroCliente: Int
        -datosPersonales: Persona
        -vehiculos: list<Vehiculos>
    }


    Class Turno{
       -diayHora: Date
       -mecanicoAsignado: Mecanico
       -personalTelefonica: bool
       -cliente: Cliente
       -vehiculo: Vehiculo
       -estado: bool
       + revisarAgenda()
       + asignarTurno()
    }


    Class Agenda{
       '-mes:int
       -anio:int
       -mecanico:Mecanico
       -turnosTotales: List<Turno>
    }


    Class FichaMecanica{
        -mecanico: Mecanico
        -cliente: Cliente
        -descripcion: string
        -dia: date
        -tiempoEmpleado:int
        -conformidad: bool
        
    }
    
    'Relaciones
    
    Empresa o-- Cliente

    Persona "1" --> "1-n" Turno
    
    
    Cliente "1" -->"1-n" Vehiculo
    Cliente --|> Persona
    
    Empleado --> Empleado
    Empleado --|> Persona
    
    Mecanico " 1" --> " 1-n" Especialidad
    Mecanico --|> Empleado
	Oficinista -right-|> Empleado
    
    FichaMecanica "1" --> "1" Mecanico
    FichaMecanica "1" --> "1" Cliente
    
    Agenda "1" *-- "0-n" Turno

}
@enduml
